- name: restart postgresql
  service:
    name: postgresql
    state: restarted

- name: pgbouncer daemon-reload
  systemd:
    name: pgbouncer
    daemon_reload: yes

- name: restart pgbouncer
  service:
    name: pgbouncer
    state: restarted