- name: Setup ssh
  include_tasks: ssh.yaml

- name: Install repmgr
  include_tasks: install.yaml
  tags: [repmgr]

- name: Configure pg cluster
  include_tasks: configure.yaml
  tags: [configure]

- name: Cluster registration
  include_tasks: registration.yaml
  tags: [registration]
