- name: Add 2ndquadrant apt key
  apt_key:
    url: https://dl.2ndquadrant.com/gpg-key.asc
    state: present

- name: Add postgres repo
  apt_repository:
    repo: "deb https://dl.2ndquadrant.com/default/release/apt {{ ansible_distribution_release }}-2ndquadrant main"
    state: present
    filename: 2ndquadrant
    update_cache: yes

- name: Install repmgr for PostgreSQL {{ postgresql_version }}
  apt:
    name: postgresql-{{ postgresql_version }}-repmgr
    update_cache: yes

- name: Setup repmgr user and database
  become_user: postgres
  ignore_errors: yes
  shell: |
    createuser --superuser repmgr &&
    psql -c 'ALTER USER repmgr SET search_path TO repmgr, public;' &&
    createdb repmgr --owner=repmgr
    exit 0

- name: Copy repmgr configuration
  template:
    src: repmgr/repmgr.conf.j2
    dest: /etc/repmgr.conf

- name: Restart PostgreSQL
  systemd:
    name: postgresql
    enabled: yes
    state: restarted